services:
  postgres:
    image: 'postgres:latest'
    container_name: books-postgres
    environment:
      - 'POSTGRES_DB=books_db'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    ports:
      - '5440:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: