ktor:
  application:
    modules:
      - com.example.ApplicationKt.module
  deployment:
    port: 8080
jwt:
  domain: ${JWT_DOMAIN}
  audience: ${JWT_AUDIENCE}
  issuer: ${JWT_ISSUER}
  realm: ${JWT_REALM}
  claimField: "id"
  secret: ${JWT_SECRET}
  accessTokenExpiration: ${JWT_ACCESS_EXPIRATION}
  refreshTokenExpiration: ${JWT_REFRESH_EXPIRATION}
database:
  url: ${DB_URL}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  driver: "org.postgresql.Driver"
mail:
  host: ${MAIL_HOST}
  port: ${MAIL_PORT}
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}
  default-encoding: UTF-8
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000
